---
title: "Oak Data Exploration"
format: html
editor: visual
---

## Oak exploratory data analysis and cleaning

```{r}
library(tidyverse)

library(readxl)
library(ggplot2)

#import the correct sheet/excel
Survival_HeightApril26Blocks7_6Clean <- read_excel("Oak Project/Data/Survival_HeightApril26Blocks7&6Clean.xlsx", 
                                                   sheet = "Input1", skip=1)
View(Survival_HeightApril26Blocks7_6Clean)

names(Survival_HeightApril26Blocks7_6Clean)
```

Rename rows

```{r}
Survival_HeightApril26Blocks7_6Clean<- Survival_HeightApril26Blocks7_6Clean |> 
  rename(Date= "MM/DD/YYYY",
                                              Page_Number = "Page #",
                                              Recorder=  "Name",
                                              Block= "#...4",
                                              Tag_Num=  "#...5",
                                              Oak_type=  "NR, S, or A",
                                              Treatment= "AC, OA, NP, DT, or DL",
                                              OA_microclimate= "TH, TI, CN",
                                              Seedling_Ht_cm= "(cm)",
                                            Num_leaves=  "#...10",
                                              Num_dead_leaves= "#...11",
                                              Leaf_greenness=  "%",
                                              Num_germinated= "#...13",
                                              RCD=  "(mm)",
                                              Notes= "as written on data sheet")
                                              
  
head(Survival_HeightApril26Blocks7_6Clean)

```

### Summarize data

Change numeric columns to numeric

```{r}
head(Survival_HeightApril26Blocks7_6Clean)

Survival_HeightApril26Blocks7_6Clean<-  Survival_HeightApril26Blocks7_6Clean |> 
  mutate(Seedling_Ht_cm = as.numeric(Seedling_Ht_cm)) |> 
  mutate(Num_leaves = as.numeric(Num_leaves)) |> 
  mutate(Num_dead_leaves = as.numeric(Num_dead_leaves))|> 
  mutate(Leaf_greenness = as.numeric(Leaf_greenness)) |> 
  mutate(Num_germinated= as.numeric(Num_germinated)) |> 
  mutate(RCD=as.numeric(RCD))
```

Summarize amounts of data

```{r}
Survival_HeightApril26Blocks7_6Clean |> 
  group_by(Oak_type) |> count()

Survival_HeightApril26Blocks7_6Clean |> 
  group_by(Treatment) |> count()

Survival_HeightApril26Blocks7_6Clean |> 
  group_by(OA_microclimate) |> count()

#Number of treatments/oak types
Survival_HeightApr_treatmentsum<- Survival_HeightApril26Blocks7_6Clean |> 
  group_by(Oak_type, Treatment) |> count()

head(Survival_HeightApril26Blocks7_6Clean)
```

Generate histograms of numeric data

```{r}
ggplot(Survival_HeightApril26Blocks7_6Clean) + 
  aes(x = Seedling_Ht_cm) +
  geom_histogram()

ggplot(Survival_HeightApril26Blocks7_6Clean) + 
  aes(x = Num_leaves) +
  geom_histogram()

ggplot(Survival_HeightApril26Blocks7_6Clean) + 
  aes(x = Num_dead_leaves) +
  geom_histogram()

ggplot(Survival_HeightApril26Blocks7_6Clean) + 
  aes(x = Leaf_greenness) +
  geom_histogram()

ggplot(Survival_HeightApril26Blocks7_6Clean) + 
  aes(x = Num_germinated) +
  geom_histogram()

ggplot(Survival_HeightApril26Blocks7_6Clean) + 
  aes(x = RCD) +
  geom_histogram()
```

Mean, max, min of numeric values

Summarize based on oak type and treatment. What are the main variables of interest?

```{r}

# Create a summary table
Survival_HeightApril26Blocks7_6Clean_summarytbl <- Survival_HeightApril26Blocks7_6Clean |> 
  group_by(Oak_type, Treatment) |> 
  summarize(
    n = n(), 
    min_SeedHt= min(Seedling_Ht_cm,na.rm=TRUE),
    mean_SeedHt = mean(Seedling_Ht_cm, na.rm=TRUE), 
    max_SeedHt= max(Seedling_Ht_cm, na.rm=TRUE),
    SD_SeedHt = sd(Seedling_Ht_cm, na.rm=TRUE)) 

Survival_HeightApril26Blocks7_6Clean_summarytbl
```

Summarize how many seedlings survived out of total planted

```{r}
Survival_HeightApril26Blocks7_6Clean |> 
  summarise(
    seed_count = sum(!is.na(Seedling_Ht_cm)),
    na_count      = sum(is.na(Seedling_Ht_cm))
  )

#29 seedlings survived, 8 did not, 78% survival

29/(8+29)
```
